import { library } from '@fortawesome/fontawesome-svg-core';
import { faTelegram } from '@fortawesome/free-brands-svg-icons';

import {
    faChevronDown,
    faChevronUp,
    faUserCircle,
    faCog,
    faSignOutAlt,
    faFolder,
    faFolderOpen,
    faChevronCircleRight,
    faChevronCircleLeft,
    faBars,
    faPencilAlt,
    faCircle,
    faDotCircle,
    faChevronRight,
    faShieldAlt,
    faTimes,
    faEllipsisH,
    faGripLines,
    faEye,
    faEyeSlash,
    faExclamationCircle,
    faCheckCircle,
    faHandHoldingUsd,
} from '@fortawesome/free-solid-svg-icons';

library.add(
    faChevronDown,
    faChevronUp,
    faUserCircle,
    faCog,
    faSignOutAlt,
    faFolder,
    faFolderOpen,
    faChevronCircleRight,
    faChevronCircleLeft,
    faBars,
    faPencilAlt,
    faCircle,
    faDotCircle,
    faChevronRight,
    faShieldAlt,
    faTelegram,
    faTimes,
    faEllipsisH,
    faGripLines,
    faEye,
    faEyeSlash,
    faCheckCircle,
    faExclamationCircle,
    faHandHoldingUsd
);
